// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"time"
)

type Comment struct {
	ID      int64
	Created time.Time
	Slug    string
	Author  string
	Content string
}

type Session struct {
	SessionKey string
	Uid        int32
	LoginTime  time.Time
	LastSeen   time.Time
}

type User struct {
	ID      int32
	Email   string
	Hash    string
	Salt    string
	IsAdmin bool
}
